### ISSUE TITLE
Twig requirements are implicit

### ISSUE THREAD

**Issue by garak** [chrisguitarguy/RequestIdBundle#10]
Since commit 26247af9e24ff9a424c2580efc6800cc9247cbed introduced a requirement for Twig, such requirement should be explicit.
Unfortunately, the commit only changed `require-dev` section, that is working only when this repository is used standalone (e.g. in testing).
For requirement to be enforced when this repository is used as a dependency, the following section should be added:
```
"conflict": {
    "twig/twig": "<1.38|>=2,<2.7"
}
```

**Comment by chrisguitarguy** [comment]
It's not a hard requirement -- that's why it's in require-dev.

I don't mind having it in `conflict`, but I'm not sure it belongs there. Nothing breaks with an incompatible twig version. The twig portion of the bundle doesn't work, sure, but that's it. I don't know that we should block an upgraded for someone who may not even be using the twig integration (which can be turned off in the config).

**Comment by garak** [comment]
The point is exactly for Twig users (if you don't use Twig, you can't be in conflict).
So, if you use unsupported versions of Twig, you likely don't want to upgrade to a version of this bundle that does not support such versions (so you can avoid to break your application, or you can simply upgrade your Twig *before* breaking)
